### ISSUE TITLE
Remove "Enabled Deferred JavaScript"

### ISSUE THREAD

**Issue by uandiweb** [magefan/module-rocketjavascript#4]
Magento 2.3.2 allows to move all JS files to the end of the page. Can you please remove this option from your extension to prevent any conflicts?

**Comment by magefan** [comment]
Hello @uandiweb , thank you for your report. 

We know that Magento has this option since Magento 2.3, but we will not remove this option from our extension for various reasons:

1. Not all merchants use Magento 2.3, some still use Magento2.0, 2.1, 2.2 and they need this option
2. Magento option does not allow to skip some <script> tags from moving to the bottom, our module does by attribute data-rocketjavascript="false"
3. This option is disabled by default when you install the extension, so this feature does not work until you enable it.

**Comment by Rohaty** [comment]
Hi,
I installed version 2.1.6, but if I put data-rocketjavascript = "false" into a GTM script, for example, the script will move to the end. At the same time, in version 2.1.4 it worked correctly and the GTM script remained in place, it did not move down.
Where is the problem?
Of course I have an enable extension.
Regards

**Comment by ihorvansach** [comment]
@Rohaty , are you sure that you have enabled Magefan RocketJS deferred JavaScript and magento default one?

**Comment by Rohaty** [comment]
Hi,
I'm sorry, I also had the core Mogento function "Move JS code to the bottom of the page" turned on. If I set "Move JS code to the bottom of the page = NO" everything works fine and the GTM script remained in place and was not moved to the bottom of the page.
My inattention, I apologize.
